language: node_js
node_js:
  - 13

services:
  - docker

script:
  - docker --version
  - docker build -t simple-node-exercise .
  - docker tag simple-node-exercise vlkrst/simple-node-exercise:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push vlkrst/simple-node-exercise